source: "youtube"
data_root: "/mnt/nas05/data02/vincenzo/podcast_data/youtube"
podcasts:
  - title: "Ein Buch Ein Tee"
    url: "https://www.youtube.com/playlist?list=PLCospSPttrrVSk0N5Mqj1dveKZtDZNOAl"
    lang: "ch"
  - title: "SRF Dokumentationen"
    url: "https://www.youtube.com/playlist?list=PLrAvDZ9sYjXYQb1Jk4TSyy6JTXbDn1JLg"
    lang: "mixed"
  - title: "SRF Reportagen"
    url: "https://www.youtube.com/playlist?list=PLrAvDZ9sYjXZ72dR3c-xdnAjRIVmTIMIG"
    lang: "mixed"
  - title: "Sexologie - Wissen macht Lust"
    url: "https://www.youtube.com/playlist?list=PL3D2QP2F5r9VDSj6YQb6Ihr_63Gxtm4L5"
    lang: "mixed"
  - title: "Ungerwegs Daheim"
    url: "https://www.youtube.com/playlist?list=PLM4IdPP-Tx3W84w1GB8cn33GnuIGcqaeP"
    lang: "ch"
  - title: "expectations - geplant und ungeplant kinderfrei"
    url: "https://www.youtube.com/playlist?list=PL5ZbqYujTUkVmNCGMP4e0yFVhY8P5EC73"
    lang: "ch"
  - title: "Wir müssen reden - Public Eye spricht Klartext"
    url: "https://www.youtube.com/playlist?list=PLtTxFB6b5Pljl4RU6vimwfQpV490K6SQe"
    lang: "de"
  - title: "FinanzFabio"
    url: "https://www.youtube.com/playlist?list=PLGJjtm2tSyhQXU-_N2YkfqCffXhY6UHNe"
    lang: "ch"
  - title: "Feel Good Podcast"
    url: "https://www.youtube.com/playlist?list=PLf-k85Nq3_j-glR2im1SZv_BxqzdYdENk"
    lang: "ch"
  - title: "Berner Jugendtreff"
    url: "https://www.youtube.com/playlist?list=PLyWje_91744G6UAsfHjTLWDtejJdHmuYv"
    lang: "ch"
  - title: "fadegrad"
    url: "https://www.youtube.com/playlist?list=PL356t1Y2d_AXycvLzBF1n8ee0uM4pw9JX"
    lang: "ch"
  - title: "Scho ghört"
    url: "https://www.youtube.com/playlist?list=PLKaFe_fDMhQNbWvnJGC6HArb285ZUdGbz"
    lang: "ch"
  - title: "Über den Bücherrand"
    url: "https://www.youtube.com/playlist?list=PLPtjJ0sjI3yzhNtZUBY0_e462_gKtr90V"
    lang: "mixed"
  - title: "Auf Bewährung: Leben mit Gefängnis"
    url: "https://www.youtube.com/playlist?list=PLAD8a6PKLsRhHc-uS6fA6HTDijwE5Uwju"
    lang: "mixed"

write_attrs_to_hdf5: false

steps:
  download: true
  diarization: false
  segmentation: false
  phon_transcription: false
  dialect_classification: false
  ch_transcription: false
  mel_spectrogram: false
  move_into_dialect_h5: false
