source: "srf"
youtube_url: "https://www.youtube.com/watch?v=XYZ123"
podcast_name: ""
write_attrs_to_hdf5: false

steps:
  download: true
  diarization: false
  segmentation: false
  phon_transcription: false
  dialect_classification: false
  ch_transcription: false
  mel_spectrogram: false
  move_into_dialect_h5: false
